import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#0a0a0a',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 100,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    marginTop: 8,
  },
  priceInfo: { flex: 1 },
  symbol: { fontSize: 16, fontWeight: '600', color: '#fff', marginBottom: 4 },
  price: { fontSize: 24, fontWeight: 'bold', color: '#fff', marginBottom: 2 },
  change: { fontSize: 14, fontWeight: '600' },
  positiveChange: { color: '#00d4aa' },
  negativeChange: { color: '#ff6b6b' },
  headerActions: { flexDirection: 'row', gap: 8 },
  headerButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  toggleContainer: { marginBottom: 16 },
  toggleBackground: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 12,
    padding: 2,
    alignItems: 'center',
  },
  toggleIndicator: {
    position: 'absolute',
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#ffd700',
    zIndex: 1,
  },
  toggleViewButton: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  toggleViewText: { fontSize: 14, fontWeight: '500' },
  graphContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
  },
  graphTitle: { fontSize: 18, fontWeight: 'bold', color: '#fff', marginBottom: 12 },
  graphBars: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    height: 120,
  },
  barContainer: { alignItems: 'center', width: 50 },
  bar: {
    width: 20,
    backgroundColor: 'rgba(255, 215, 0, 0.2)',
    borderRadius: 10,
    marginBottom: 8,
  },
  barLabel: { fontSize: 12, color: '#999' },
  barAmount: { fontSize: 14, fontWeight: '600', color: '#fff' },
  cardsContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
  },
  cardsTitle: { fontSize: 18, fontWeight: 'bold', color: '#fff', marginBottom: 12 },
  transactionCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
  },
  cardLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  cardIcon: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  cardInfo: { gap: 2 },
  cardTitle: { fontSize: 16, fontWeight: '600', color: '#fff' },
  cardDate: { fontSize: 12, color: '#999' },
  cardAmount: { fontSize: 16, fontWeight: '600', color: '#ff6b6b' },
  walletContainer: { marginBottom: 16 },
  walletCard: { backgroundColor: 'rgba(255, 255, 255, 0.05)', borderRadius: 16, padding: 20 },
  walletGradient: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    borderRadius: 12,
  },
  walletHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  walletTitle: { fontSize: 16, fontWeight: '600', color: '#fff' },
  walletAmount: { fontSize: 28, fontWeight: 'bold', color: '#fff', marginTop: 4 },
  walletCurrency: { fontSize: 16, color: '#999' },
  todaySpentCard: { backgroundColor: 'rgba(255, 255, 255, 0.05)', borderRadius: 16, padding: 20, marginBottom: 16 },
  todaySpentHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  todaySpentTitle: { fontSize: 16, fontWeight: '600', color: '#fff' },
  todaySpentAmount: { fontSize: 28, fontWeight: 'bold', color: '#ff6b6b', marginBottom: 4 },
  todaySpentLabel: { fontSize: 14, color: '#999' },
  spendingBreakdown: { backgroundColor: 'rgba(255, 255, 255, 0.05)', borderRadius: 16, padding: 20 },
  breakdownTitle: { fontSize: 18, fontWeight: 'bold', color: '#fff', marginBottom: 12 },
  breakdownItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  breakdownLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  breakdownIcon: { width: 24, height: 24, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  breakdownText: { fontSize: 14, color: '#fff' },
  breakdownAmount: { fontSize: 14, fontWeight: '600', color: '#ff6b6b' },
  balanceCard: { backgroundColor: 'rgba(255, 255, 255, 0.05)', borderRadius: 16, padding: 20, marginBottom: 16 },
  balanceHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  balanceLabel: { fontSize: 14, color: '#999' },
  balanceAmount: { fontSize: 28, fontWeight: 'bold', color: '#fff', marginBottom: 4 },
  currencyText: { fontSize: 18, color: '#ffd700' },
  balanceFiat: { fontSize: 16, color: '#999' },
  viewToggle: { flexDirection: 'row', backgroundColor: 'rgba(255, 255, 255, 0.05)', borderRadius: 12, padding: 4, marginBottom: 16 },
  toggleButton: { flex: 1, paddingVertical: 8, paddingHorizontal: 12, borderRadius: 8, alignItems: 'center' },
  toggleButtonActive: { backgroundColor: 'rgba(255, 215, 0, 0.2)' },
  toggleText: { fontSize: 14, color: '#999', fontWeight: '500' },
  toggleTextActive: { color: '#ffd700', fontWeight: '600' },
  cardContainer: { minHeight: 400, position: 'relative' },
  card: {
    position: 'absolute', top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.05)', borderRadius: 16, padding: 20, backfaceVisibility: 'hidden',
  },
  tradingView: { flex: 1 },
  tradeSection: { marginBottom: 24 },
  tradeHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  tradeLabel: { fontSize: 16, fontWeight: '600', color: '#fff' },
  availableBalance: { fontSize: 12, color: '#999' },
  inputContainer: {
    flexDirection: 'row', backgroundColor: 'rgba(255, 255, 255, 0.05)', borderRadius: 12,
    paddingHorizontal: 16, paddingVertical: 12, marginBottom: 12, alignItems: 'center',
  },
  amountInput: { flex: 1, fontSize: 18, color: '#fff', paddingVertical: 0 },
  currencyButton: { backgroundColor: 'rgba(255, 215, 0, 0.2)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8 },
  currencyButtonText: { fontSize: 14, fontWeight: '600', color: '#ffd700' },
  percentageButtons: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  percentageButton: {
    flex: 1, paddingVertical: 8, paddingHorizontal: 12, borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.05)', alignItems: 'center', marginHorizontal: 2,
  },
  percentageButtonActive: { backgroundColor: 'rgba(0, 212, 170, 0.2)' },
  percentageButtonText: { fontSize: 12, color: '#999', fontWeight: '500' },
  percentageButtonTextActive: { color: '#00d4aa', fontWeight: '600' },
  percentageButtonActiveSell: { backgroundColor: 'rgba(255, 107, 107, 0.2)' },
  percentageButtonTextActiveSell: { color: '#ff6b6b', fontWeight: '600' },
  buyButton: { borderRadius: 12, overflow: 'hidden' },
  buyGradient: { paddingVertical: 16, alignItems: 'center' },
  buyButtonText: { fontSize: 16, fontWeight: 'bold', color: '#fff' },
  sellButton: { borderRadius: 12, overflow: 'hidden' },
  sellGradient: { paddingVertical: 16, alignItems: 'center' },
  sellButtonText: { fontSize: 16, fontWeight: 'bold', color: '#fff' },
  divider: { height: 1, backgroundColor: 'rgba(255, 255, 255, 0.1)', marginVertical: 16 },
  portfolioView: { flex: 1 },
  portfolioHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  portfolioTitle: { fontSize: 18, fontWeight: 'bold', color: '#fff' },
  refreshButton: {
    width: 36, height: 36, borderRadius: 18, backgroundColor: 'rgba(255, 255, 255, 0.1)', alignItems: 'center', justifyContent: 'center',
  },
  assetItem: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 16,
    borderBottomWidth: 1, borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  assetInfo: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  assetIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255, 215, 0, 0.2)', alignItems: 'center', justifyContent: 'center' },
  assetIconText: { fontSize: 18, fontWeight: 'bold', color: '#ffd700' },
  assetDetails: { gap: 2 },
  assetName: { fontSize: 16, fontWeight: '600', color: '#fff' },
  assetSymbol: { fontSize: 14, color: '#999' },
  assetValue: { alignItems: 'flex-end', gap: 2 },
  assetAmount: { fontSize: 16, fontWeight: '600', color: '#fff' },
  assetPrice: { fontSize: 14, color: '#999' },
  orderbookView: { flex: 1 },
  orderbookHeader: { alignItems: 'center', marginBottom: 20 },
  orderbookTitle: { fontSize: 18, fontWeight: 'bold', color: '#fff', marginBottom: 4 },
  orderbookSubtitle: { fontSize: 14, color: '#999' },
  orderbookContent: { flex: 1 },
  orderbookColumn: {
    flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: 'rgba(255, 255, 255, 0.1)', marginBottom: 12,
  },
  orderbookLabel: { fontSize: 12, color: '#999', fontWeight: '500' },
  sellOrders: { marginBottom: 16 },
  orderRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 6 },
  sellPrice: { fontSize: 14, color: '#ff6b6b', fontWeight: '500' },
  buyPrice: { fontSize: 14, color: '#00d4aa', fontWeight: '500' },
  orderAmount: { fontSize: 14, color: '#fff' },
  currentPriceRow: { alignItems: 'center', paddingVertical: 12, backgroundColor: 'rgba(255, 215, 0, 0.1)', borderRadius: 8, marginVertical: 8 },
  currentPrice: { fontSize: 18, fontWeight: 'bold', color: '#ffd700', marginBottom: 2 },
  currentPriceLabel: { fontSize: 12, color: '#999' },
  quickActionsView: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  quickActionsTitle: { fontSize: 20, fontWeight: 'bold', color: '#fff', marginBottom: 24 },
  quickActionsGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', width: '100%', marginBottom: 32 },
  quickActionButton: { width: '48%', alignItems: 'center', marginBottom: 16 },
  quickActionGradient: { width: 60, height: 60, borderRadius: 30, alignItems: 'center', justifyContent: 'center', marginBottom: 8 },
  quickActionText: { fontSize: 12, color: '#fff', textAlign: 'center' },
  flipBackButton: { backgroundColor: 'rgba(255, 255, 255, 0.1)', paddingHorizontal: 24, paddingVertical: 12, borderRadius: 12 },
  flipBackButtonText: { fontSize: 16, fontWeight: '600', color: '#fff' },
  bottomSpacing: { height: 20 },
  flipButton: {
    position: 'absolute', bottom: 20, right: 20, borderRadius: 25, overflow: 'hidden', elevation: 5,
    shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.25, shadowRadius: 3.84,
  },
  flipButtonGradient: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 12, gap: 8 },
  flipButtonText: { fontSize: 14, fontWeight: 'bold', color: '#000' },
});


